name: TConsumeArgentina
env:
  TWITTER_CONSUMER_KEY:  ${{ secrets.twitter_consumer_key }}
  TWITTER_CONSUMER_SECRET:  ${{ secrets.twitter_consumer_secret }}
  TWITTER_ACCESS_TOKEN:  ${{ secrets.twitter_access_token }}
  TWITTER_ACCESS_TOKEN_SECRET:  ${{ secrets.twitter_access_token_secret }}
on:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tweet Consumer 
      run: python consume_reporter_argentina.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET}
