name: Demanda_Provincias_NOA
env:
  TWITTER_CONSUMER_KEY:  ${{ secrets.twitter_consumer_key }}
  TWITTER_CONSUMER_SECRET:  ${{ secrets.twitter_consumer_secret }}
  TWITTER_ACCESS_TOKEN:  ${{ secrets.twitter_access_token }}
  TWITTER_ACCESS_TOKEN_SECRET:  ${{ secrets.twitter_access_token_secret }}
on:
  schedule:
    - cron: '10 */3 * * *'
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tweet Consumer Salta 
      run: python consume_reporter_provincias.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET} "Salta"
    - name: Tweet Consumer Tucuman 
      run: python consume_reporter_provincias.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET} "Tucuman"
    - name: Tweet Consumer Jujuy 
      run: python consume_reporter_provincias.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET} "Jujuy"
    - name: Tweet Consumer Santiago del Estero 
      run: python consume_reporter_provincias.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET} "Santiago del Estero"
    - name: Tweet Consumer Catamarca 
      run: python consume_reporter_provincias.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET} "Catamarca"
    - name: Tweet Consumer La Rioja 
      run: python consume_reporter_provincias.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET} "La Rioja"

