name: TConsumeProvincias
env:
  TWITTER_CONSUMER_KEY:  ${{ secrets.twitter_consumer_key }}
  TWITTER_CONSUMER_SECRET:  ${{ secrets.twitter_consumer_secret }}
  TWITTER_ACCESS_TOKEN:  ${{ secrets.twitter_access_token }}
  TWITTER_ACCESS_TOKEN_SECRET:  ${{ secrets.twitter_access_token_secret }}
on:
  schedule:
    - cron: '10 */3 * * *'
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tweet Consumer Cordoba 
      run: python consume_reporter_provincias.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET} "Cordoba"
    - name: Tweet Consumer Tucuman 
      run: python consume_reporter_provincias.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET} "Tucuman"
    - name: Tweet Consumer Mendoza 
      run: python consume_reporter_provincias.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET} "Mendoza"
    - name: Tweet Consumer Santiago del Estero 
      run: python consume_reporter_provincias.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET} "Santiago del Estero"
