name: Demanda_MW_Argentina
env:
  TWITTER_CONSUMER_KEY:  ${{ secrets.twitter_consumer_key }}
  TWITTER_CONSUMER_SECRET:  ${{ secrets.twitter_consumer_secret }}
  TWITTER_ACCESS_TOKEN:  ${{ secrets.twitter_access_token }}
  TWITTER_ACCESS_TOKEN_SECRET:  ${{ secrets.twitter_access_token_secret }}
on:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  tweet:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: local-fix
      run: |
        # Hack to get setup-python to work on act
        # (see https://github.com/nektos/act/issues/251)
        if [ ! -f "/etc/lsb-release" ] ; then
          echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
        fi
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tweet Consumer 
      run: python3 consume_reporter_argentina.py ${TWITTER_CONSUMER_KEY} ${TWITTER_CONSUMER_SECRET} ${TWITTER_ACCESS_TOKEN} ${TWITTER_ACCESS_TOKEN_SECRET}
